### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Sebight** [TeodorVecerdi/DialogueGraph#6]
Hello, 

this tool seems to error when we try to build our game. Because the huge use-case of this tool, I would like to try to get this fixed.

The errors originate from Drawer.cs script and look like this: 
![obrazek](https://user-images.githubusercontent.com/59232422/158685504-b125d542-171e-44d4-bf86-0dfd3dcc3d0c.png)

Sadly, I cannot build the game without this. I'd really like to try to fix this together, so I can use this great tool in our game.

Thank you

**Comment by Sebight** [comment]
Hello,

thank you for the swift response. We currently use **2021.2.8f1**.

It might be with the version, we opted to use the new ones, but it seems to only cause problems so far.

Thank you

**Comment by TeodorVecerdi** [comment]
I fixed the issue and made a new [release](https://github.com/TeodorVecerdi/DialogueGraph/releases/tag/1.1.5).
If you installed Dialogue Graph using OpenUPM it will take a few minutes until it updates there.

I'm going to close this issue, but feel free to re-open it if the problem persists or create a new one if you find another problem.
Thank you for using Dialogue Graph!
